import { queryOptions } from "@tanstack/react-query"
import { notFound } from "@tanstack/react-router"

import type { BrowseCategory, DetailItem } from "../warframe"
import { staticDataQuery } from "./static-data-query"

/** Slugs are generated by the data pipeline and are always lowercase
 *  alphanumeric + dashes. Anything else is a hand-crafted URL: without this
 *  check a `../`-bearing slug normalizes to a different `/data/*.json` file
 *  and feeds wrong-shaped JSON into the editor instead of 404ing. */
const SLUG_RE = /^[a-z0-9-]+$/

export const itemQuery = (category: BrowseCategory, slug: string) => {
  if (!SLUG_RE.test(slug)) {
    return queryOptions<DetailItem>({
      queryKey: ["item", category, slug],
      queryFn: () => {
        throw notFound()
      },
      staleTime: Infinity,
      gcTime: Infinity,
    })
  }
  return staticDataQuery<DetailItem>(
    ["item", category, slug],
    `/data/items/${category}/${encodeURIComponent(slug)}.json`,
    "failed to load item",
    { notFoundOn404: true },
  )
}
