// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//
// Prisma (via dotenv) only auto-loads `.env` by default, but Next.js commonly
// uses `.env.local` for local development. Load both so Prisma commands work
// without duplicating env vars.
import fs from "node:fs";
import path from "node:path";
import dotenv from "dotenv";
import { defineConfig, env } from "prisma/config";

const rootDir = process.cwd();

for (const filename of [".env.local", ".env"]) {
  const fullPath = path.join(rootDir, filename);
  if (fs.existsSync(fullPath)) {
    dotenv.config({ path: fullPath });
  }
}

// Allow Prisma commands (e.g. `prisma generate` during install) to work on a
// fresh clone by falling back to `.env.example` for DATABASE_URL.
if (!process.env.DATABASE_URL) {
  const examplePath = path.join(rootDir, ".env.example");
  if (fs.existsSync(examplePath)) {
    dotenv.config({ path: examplePath });
  }
}

// `prisma generate` only needs a syntactically valid URL. Default to a local
// placeholder so dependency updates and installs can run before local env setup.
process.env.DATABASE_URL ??= "postgresql://postgres:postgres@localhost:5432/arsenyx";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
